[2024-10-13T00:05:08.760+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T00:05:08.768+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_crypto_data_redshift.insert_crypto_data_redshift scheduled__2024-10-12T00:00:00+00:00 [queued]>
[2024-10-13T00:05:08.771+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_crypto_data_redshift.insert_crypto_data_redshift scheduled__2024-10-12T00:00:00+00:00 [queued]>
[2024-10-13T00:05:08.772+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-13T00:05:08.777+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_crypto_data_redshift> on 2024-10-12 00:00:00+00:00
[2024-10-13T00:05:08.788+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2970) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-13T00:05:08.794+0000] {standard_task_runner.py:72} INFO - Started process 2972 to run task
[2024-10-13T00:05:08.797+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'insert_crypto_data_redshift', 'insert_crypto_data_redshift', 'scheduled__2024-10-12T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpn6pxwvuc']
[2024-10-13T00:05:08.801+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask insert_crypto_data_redshift
[2024-10-13T00:05:08.837+0000] {task_command.py:467} INFO - Running <TaskInstance: insert_crypto_data_redshift.insert_crypto_data_redshift scheduled__2024-10-12T00:00:00+00:00 [running]> on host 9e38755235ef
[2024-10-13T00:05:08.881+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='insert_crypto_data_redshift' AIRFLOW_CTX_TASK_ID='insert_crypto_data_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T00:00:00+00:00'
[2024-10-13T00:05:08.882+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T00:05:09.175+0000] {logging_mixin.py:190} INFO -    tipo  compra  venta                     fecha
0  Blue    1160   1180  2024-10-12T20:58:00.000Z
[2024-10-13T00:05:14.488+0000] {logging_mixin.py:190} INFO - Error al obtener el precio para BTCUSDT: 400 Client Error: Bad Request for url: https://api.api-ninjas.com/v1/cryptoprice?symbol=BTCUSDT
[2024-10-13T00:05:14.496+0000] {logging_mixin.py:190} INFO - BTCUSDT
[2024-10-13T00:05:14.500+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 76, in insert_crypto_data
    crypto_prices.at[row, 'price_USD'] = round(float(price), 3)
                                               ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[2024-10-13T00:05:14.533+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=insert_crypto_data_redshift, task_id=insert_crypto_data_redshift, run_id=scheduled__2024-10-12T00:00:00+00:00, execution_date=20241012T000000, start_date=20241013T000508, end_date=20241013T000514
[2024-10-13T00:05:14.550+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T00:05:14.551+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task insert_crypto_data_redshift (float() argument must be a string or a real number, not 'NoneType'; 2972)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 76, in insert_crypto_data
    crypto_prices.at[row, 'price_USD'] = round(float(price), 3)
                                               ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[2024-10-13T00:05:14.585+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T00:05:14.605+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T00:05:14.607+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
